CFLAGS= -g
CC=g++

all: sqlite3 client server 

# To make an executable
sqlite3: sqlite3.c 
	$gcc sqlite3.c -c 

client: client.cpp
	$(CC) client.cpp -o client 

server: server.cpp
	$(CC) server.cpp -std=c++11 -ldl -pthread sqlite3.o -o server 
 
# To make an object from source
#.c.o:
#	$gcc $sqlite3.c -c

# clean out the dross
#clean:
#	-rm boundedBuffer condvar1 profStud oneLane *.o
